version: "3.9"

services:
  db:
    container_name: postgres
    image: postgres:13
    restart: always
    networks:
      - risevest-network
    environment:
      - POSTGRES_DB=risevest_db
      - POSTGRES_USER=olamide
      - POSTGRES_PASSWORD=admin
      - POSTGRES_INITDB_ARGS=--data-checksums
    volumes:
      - postgres_data:/var/lib/postgresql/data/

  app:
    container_name: app
    build:
      context: .
    restart: unless-stopped
    ports: ["8080:8080"]
    networks:
      - risevest-network
    volumes:
      - ./src:/app/src:cached
    env_file: [./.env]
    depends_on: ["db"]

networks:
  risevest-network:

volumes:
  postgres_data:
